apiVersion: v1
kind: Service
metadata:
  name: visio-to-svg-converter
spec:
  selector:
    app: visio-to-svg-converter
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  type: LoadBalancer
